# Generated by Django 5.1.15 on 2026-09-29 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in app"),
                            ("import", "Imported (Excel)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "legacy_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Row/sheet reference from the original Excel file, used to avoid duplicate imports.",
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("bank", "Bank transfer / NEFT"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Transaction / cheque no.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "followup_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("call", "Phone call"),
                            ("whatsapp", "WhatsApp (manual)"),
                            ("email", "Email"),
                            ("in_person", "In person"),
                            ("sms", "SMS"),
                            ("other", "Other"),
                        ],
                        default="call",
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "promised_payment_date",
                    models.DateField(
                        blank=True,
                        help_text="If the hospital committed to a date, reminders pause until then.",
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-followup_date", "-id"],
            },
        ),
    ]
