# Generated by Django 5.1.15 on 2026-10-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentfollowup",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Who you spoke to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to="contacts.contact",
            ),
        ),
    ]
