# Generated by Django 5.1.15 on 2026-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentfollowup_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.CharField(
                blank=True,
                help_text="Who received the payment, e.g. Dr. Mehta, clinic staff, bank account.",
                max_length=100,
            ),
        ),
    ]
