# Generated by Django 5.1.15 on 2026-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_received_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentfollowup",
            name="next_reminder",
            field=models.DateField(
                blank=True,
                help_text="Get a payment reminder on this date. Leave empty for no more reminders.",
                null=True,
                verbose_name="Remind me again on",
            ),
        ),
        migrations.AlterField(
            model_name="paymentfollowup",
            name="promised_payment_date",
            field=models.DateField(
                blank=True,
                help_text="If the hospital committed to a date, you are reminded on that date.",
                null=True,
            ),
        ),
    ]
