# Generated by Django 5.1.15 on 2026-10-01 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hospitals", "0002_department_remove_hospital_contact_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                (
                    "alt_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Other phone"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("billing", "Billing"),
                            ("accounts", "Accounts"),
                            ("ot", "OT in-charge"),
                            ("consultant", "Consultant / surgeon"),
                            ("admin", "Administration"),
                            ("other", "Other"),
                        ],
                        default="billing",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Main contact"),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="contacts.contact",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty if they handle all departments.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospitals.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_links",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-start_date"],
            },
        ),
    ]
