# Generated by Django 5.1.15 on 2026-10-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("contacts", "0001_initial"),
        ("hospitals", "0003_seed_departments_and_starter_hospitals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Surgeon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Mobile"),
                ),
                ("speciality", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeons",
                        to="accounts.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SurgeonHospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeon_links",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_links",
                        to="contacts.surgeon",
                    ),
                ),
            ],
            options={
                "ordering": ["hospital__name"],
            },
        ),
        migrations.AddField(
            model_name="surgeon",
            name="hospitals",
            field=models.ManyToManyField(
                related_name="surgeons",
                through="contacts.SurgeonHospital",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddConstraint(
            model_name="surgeonhospital",
            constraint=models.UniqueConstraint(
                fields=("surgeon", "hospital"), name="unique_surgeon_hospital"
            ),
        ),
    ]
