# Generated by Django 5.1.15 on 2026-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_surgeon_surgeonhospital_surgeon_hospitals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactaffiliation",
            name="department",
        ),
    ]
