# Generated by Django 5.1.15 on 2026-09-29 07:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "practice_name",
                    models.CharField(default="Payments Tracker", max_length=120),
                ),
                (
                    "default_payment_terms_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="A case becomes Overdue this many days after the case date (unless the hospital has its own payment terms).",
                    ),
                ),
                (
                    "reminder_days",
                    models.CharField(
                        default="7,14,21",
                        help_text="Follow-up reminders are raised when an unpaid case reaches these ages (days after case date).",
                        max_length=100,
                        validators=[core.models.validate_reminder_days],
                    ),
                ),
                (
                    "repeat_reminder_every_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="After the last reminder above, keep reminding at this interval. 0 = stop.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App settings",
                "verbose_name_plural": "App settings",
            },
        ),
    ]
