# Generated by Django 5.1.15 on 2026-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="allow_signups",
            field=models.BooleanField(
                default=True,
                help_text="Shows a 'Create an account' link on the sign-in page.",
                verbose_name="Allow new doctors to sign up",
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="signup_requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="New accounts stay inactive until an admin ticks 'Active' on the Doctors page.",
                verbose_name="New sign-ups need admin approval",
            ),
        ),
    ]
