# Generated by Django 5.1.15 on 2026-10-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appsettings_allow_signups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="default_payment_terms_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Used when a case has no expected payment date: it becomes Overdue this many days after the case date.",
            ),
        ),
    ]
