# Generated by Django 5.1.15 on 2026-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_appsettings_default_payment_terms_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsettings",
            name="reminder_days",
        ),
        migrations.RemoveField(
            model_name="appsettings",
            name="repeat_reminder_every_days",
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="default_payment_terms_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Used when a case has no expected payment date. The payment reminder is sent on that date, and the case becomes Overdue after it.",
            ),
        ),
    ]
