# Generated by Django 5.1.15 on 2026-10-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_appsettings_reminder_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="notifications_last_run",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the automatic reminder sender last ran (set by send_notifications).",
                null=True,
            ),
        ),
    ]
