# Generated by Django 5.1.15 on 2026-09-29 07:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in app"),
                            ("import", "Imported (Excel)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "legacy_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Row/sheet reference from the original Excel file, used to avoid duplicate imports.",
                        max_length=100,
                    ),
                ),
                (
                    "case_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "patient_reference",
                    models.CharField(
                        blank=True,
                        help_text="IP number, initials or bill number - no clinical details needed.",
                        max_length=100,
                        verbose_name="Case / patient ref",
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Procedure / case type"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Payment expected by. Auto-calculated from hospital/global payment terms if left blank.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("followup_snoozed_until", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-case_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "case_date"],
                        name="cases_case_doctor__a0ee8a_idx",
                    )
                ],
            },
        ),
    ]
