# Generated by Django 5.1.15 on 2026-10-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("contacts", "0001_initial"),
        ("hospitals", "0002_department_remove_hospital_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Person to contact about this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="hospitals.department",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="due_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If left empty, it is set to the default payment period (30 days) after the case date.",
                null=True,
                verbose_name="Expected payment date",
            ),
        ),
    ]
