# Generated by Django 5.1.15 on 2026-10-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_contact_case_department_alter_case_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="patient_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
