# Generated by Django 5.1.15 on 2026-10-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_patient_name"),
        ("contacts", "0002_surgeon_surgeonhospital_surgeon_hospitals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="surgeon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="contacts.surgeon",
            ),
        ),
    ]
