# Generated by Django 5.1.15 on 2026-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_surgeon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="department",
        ),
    ]
