# Generated by Django 5.1.15 on 2026-09-29 07:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered in app"),
                            ("import", "Imported (Excel)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "legacy_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Row/sheet reference from the original Excel file, used to avoid duplicate imports.",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Location / address"),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "default_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Pre-filled when this hospital is picked for a new case.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_terms_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days this hospital normally takes to pay. Leave blank to use the global setting.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
