# Generated by Django 5.1.15 on 2026-10-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="default_fee",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="payment_terms_days",
        ),
        migrations.AddField(
            model_name="hospital",
            name="aliases",
            field=models.CharField(
                blank=True,
                help_text="Short or old names people search for, comma separated (e.g. KEM, Deenanath).",
                max_length=300,
                verbose_name="Other names",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="area",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Area / locality"
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="category",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("nursing_home", "Nursing home"),
                    ("clinic", "Clinic"),
                    ("day_care", "Day-care / surgical centre"),
                    ("other", "Other"),
                ],
                default="hospital",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="district",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="hospital",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this entry was a duplicate of another hospital.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("government", "Government"),
                    ("private", "Private"),
                    ("trust", "Trust / charitable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="phone",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Main phone"
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, verbose_name="PIN code"),
        ),
        migrations.AddField(
            model_name="hospital",
            name="verified",
            field=models.BooleanField(default=False, help_text="Checked by an admin."),
        ),
        migrations.AddField(
            model_name="hospital",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="city",
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="legacy_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="Source reference",
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="source",
            field=models.CharField(
                choices=[
                    ("directory", "Government directory (data.gov.in)"),
                    ("starter", "Starter list"),
                    ("doctor", "Added by a doctor"),
                    ("admin", "Added by admin"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(
                fields=["city", "name"], name="hospitals_h_city_ac63cf_idx"
            ),
        ),
    ]
