# Generated by Django 5.1.15 on 2026-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_remove_case_department"),
        ("contacts", "0003_remove_contactaffiliation_department"),
        ("hospitals", "0003_seed_departments_and_starter_hospitals"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
