# Generated by Django 5.1.15 on 2026-09-30 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Push notifications"
                    ),
                ),
                ("daily_summary", models.BooleanField(default=True)),
                ("followup_reminders", models.BooleanField(default=True)),
                ("overdue_alerts", models.BooleanField(default=True)),
                ("weekly_report", models.BooleanField(default=True)),
                ("payment_updates", models.BooleanField(default=True)),
                (
                    "summary_hour",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "5:00 AM"),
                            (6, "6:00 AM"),
                            (7, "7:00 AM"),
                            (8, "8:00 AM"),
                            (9, "9:00 AM"),
                            (10, "10:00 AM"),
                            (11, "11:00 AM"),
                            (12, "12:00 PM"),
                            (13, "1:00 PM"),
                            (14, "2:00 PM"),
                            (15, "3:00 PM"),
                            (16, "4:00 PM"),
                            (17, "5:00 PM"),
                            (18, "6:00 PM"),
                            (19, "7:00 PM"),
                            (20, "8:00 PM"),
                            (21, "9:00 PM"),
                            (22, "10:00 PM"),
                        ],
                        default=9,
                        help_text="Also the time for follow-up reminders, overdue alerts and the weekly report.",
                        verbose_name="Morning summary time",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True)),
                ("p256dh", models.CharField(max_length=200)),
                ("auth", models.CharField(max_length=100)),
                ("device", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotifiedCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="unique_notified_case_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                (
                    "key",
                    models.CharField(
                        help_text="De-duplication key, e.g. daily:2026-09-30",
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(max_length=300)),
                ("url", models.CharField(default="/", max_length=200)),
                ("devices", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="unique_notification_key_per_user"
                    )
                ],
            },
        ),
    ]
