# Generated by Django 5.1.15 on 2026-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationpreference",
            name="overdue_alerts",
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="summary_hour",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "5:00 AM"),
                    (6, "6:00 AM"),
                    (7, "7:00 AM"),
                    (8, "8:00 AM"),
                    (9, "9:00 AM"),
                    (10, "10:00 AM"),
                    (11, "11:00 AM"),
                    (12, "12:00 PM"),
                    (13, "1:00 PM"),
                    (14, "2:00 PM"),
                    (15, "3:00 PM"),
                    (16, "4:00 PM"),
                    (17, "5:00 PM"),
                    (18, "6:00 PM"),
                    (19, "7:00 PM"),
                    (20, "8:00 PM"),
                    (21, "9:00 PM"),
                    (22, "10:00 PM"),
                ],
                default=9,
                help_text="Payment reminders, the morning summary and the weekly report are sent at this time.",
                verbose_name="Notification time",
            ),
        ),
    ]
